# MinMax
* model_01

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./data/2011_2020_m2.ver2.csv', encoding='utf-8')
df

,일시,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,특보강도,남은시간
0,2011-03-04 17:00:00,2.8,8.9,0.3,0.5,1021.0,0.0,0.0
1,2011-03-04 18:00:00,3.4,8.9,0.3,0.4,1021.7,0.0,0.0
2,2011-03-04 19:00:00,4.5,8.9,0.3,0.4,1022.2,0.0,0.0
3,2011-03-04 20:00:00,2.9,8.9,0.3,0.5,1022.6,0.0,0.0
4,2011-03-04 21:00:00,3.8,8.9,0.3,0.5,1023.1,0.0,0.0
...,...,...,...,...,...,...,...,...
72644,2018-10-06 06:00:00,13.6,22.6,2.9,4.1,998.4,2.0,12.0
72645,2018-10-06 07:00:00,14.5,22.6,3.3,4.7,996.3,2.0,11.0
72646,2018-10-06 08:00:00,17.7,23.9,4.7,6.7,993.3,2.0,10.0
72647,2018-10-06 09:00:00,16.8,24.1,3.6,5.1,990.2,2.0,9.0
72648,2018-10-06 10:00:00,25.4,35.6,5.6,7.8,986.6,2.0,8.0

In [4]:
df_tgt = df[['WIND_SPEED', 'GUST_WIND', 'SIG_WAVE', 'MAX_WAVE', 'HPA']]

In [5]:
print('feature들의 최소 값')
print(df_tgt.min())
print('\nfeature들의 최대 값')
print(df_tgt.max())

feature들의 최소 값
WIND_SPEED      0.0
GUST_WIND       0.7
SIG_WAVE        0.0
MAX_WAVE        0.0
HPA           981.7
dtype: float64

feature들의 최대 값
WIND_SPEED      25.4
GUST_WIND       35.6
SIG_WAVE         5.6
MAX_WAVE         7.8
HPA           1038.0
dtype: float64

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
# MinMaxScaler객체 생성
scaler = MinMaxScaler()

In [8]:
# # MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.  
# scaler.fit(df_tgt)
# df_scaled = scaler.transform(df_tgt)

In [9]:
scaler.fit(df_tgt)

MinMaxScaler()

In [10]:
arr = scaler.transform(df_tgt)

In [11]:
df1 = pd.DataFrame(arr, columns=df_tgt.columns)
df1

       WIND_SPEED  GUST_WIND  SIG_WAVE  MAX_WAVE       HPA
0        0.110236   0.234957  0.053571  0.064103  0.698046
1        0.133858   0.234957  0.053571  0.051282  0.710480
2        0.177165   0.234957  0.053571  0.051282  0.719361
3        0.114173   0.234957  0.053571  0.064103  0.726465
4        0.149606   0.234957  0.053571  0.064103  0.735346
...           ...        ...       ...       ...       ...
72644    0.535433   0.627507  0.517857  0.525641  0.296625
72645    0.570866   0.627507  0.589286  0.602564  0.259325
72646    0.696850   0.664756  0.839286  0.858974  0.206039
72647    0.661417   0.670487  0.642857  0.653846  0.150977
72648    1.000000   1.000000  1.000000  1.000000  0.087034

[72649 rows x 5 columns]

In [12]:
df1 = pd.concat([df1,df[['일시','특보강도','남은시간']]], axis=1)
df1

,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,일시,특보강도,남은시간
0,0.110236,0.234957,0.053571,0.064103,0.698046,2011-03-04 17:00:00,0.0,0.0
1,0.133858,0.234957,0.053571,0.051282,0.710480,2011-03-04 18:00:00,0.0,0.0
2,0.177165,0.234957,0.053571,0.051282,0.719361,2011-03-04 19:00:00,0.0,0.0
3,0.114173,0.234957,0.053571,0.064103,0.726465,2011-03-04 20:00:00,0.0,0.0
4,0.149606,0.234957,0.053571,0.064103,0.735346,2011-03-04 21:00:00,0.0,0.0
...,...,...,...,...,...,...,...,...
72644,0.535433,0.627507,0.517857,0.525641,0.296625,2018-10-06 06:00:00,2.0,12.0
72645,0.570866,0.627507,0.589286,0.602564,0.259325,2018-10-06 07:00:00,2.0,11.0
72646,0.696850,0.664756,0.839286,0.858974,0.206039,2018-10-06 08:00:00,2.0,10.0
72647,0.661417,0.670487,0.642857,0.653846,0.150977,2018-10-06 09:00:00,2.0,9.0
72648,1.000000,1.000000,1.000000,1.000000,0.087034,2018-10-06 10:00:00,2.0,8.0

In [13]:
print('feature 들의 평균 값')
print(df1.mean())
print('\nfeature 들의 분산 값')
print(df1.var())

feature 들의 평균 값
WIND_SPEED    0.181486
GUST_WIND     0.273977
SIG_WAVE      0.065183
MAX_WAVE      0.072489
HPA           0.587804
특보강도          0.090504
남은시간          1.444576
dtype: float64

feature 들의 분산 값
WIND_SPEED     0.009035
GUST_WIND      0.016316
SIG_WAVE       0.003715
MAX_WAVE       0.003948
HPA            0.017488
특보강도           0.094124
남은시간          41.097588
dtype: float64

C:\Users\dbwjd\AppData\Local\Temp\ipykernel_22952\2957119008.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df1.mean())
C:\Users\dbwjd\AppData\Local\Temp\ipykernel_22952\2957119008.py:4: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df1.var())

In [23]:
df1

,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,일시,특보강도,남은시간
0,0.110236,0.234957,0.053571,0.064103,0.698046,2011-03-04 17:00:00,0.0,0.0
1,0.133858,0.234957,0.053571,0.051282,0.710480,2011-03-04 18:00:00,0.0,0.0
2,0.177165,0.234957,0.053571,0.051282,0.719361,2011-03-04 19:00:00,0.0,0.0
3,0.114173,0.234957,0.053571,0.064103,0.726465,2011-03-04 20:00:00,0.0,0.0
4,0.149606,0.234957,0.053571,0.064103,0.735346,2011-03-04 21:00:00,0.0,0.0
...,...,...,...,...,...,...,...,...
72644,0.535433,0.627507,0.517857,0.525641,0.296625,2018-10-06 06:00:00,2.0,12.0
72645,0.570866,0.627507,0.589286,0.602564,0.259325,2018-10-06 07:00:00,2.0,11.0
72646,0.696850,0.664756,0.839286,0.858974,0.206039,2018-10-06 08:00:00,2.0,10.0
72647,0.661417,0.670487,0.642857,0.653846,0.150977,2018-10-06 09:00:00,2.0,9.0
72648,1.000000,1.000000,1.000000,1.000000,0.087034,2018-10-06 10:00:00,2.0,8.0

In [24]:
df1['일시'] = pd.to_datetime(df1['일시'])
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72649 entries, 0 to 72648
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   WIND_SPEED  72649 non-null  float64
 1   GUST_WIND   72649 non-null  float64
 2   SIG_WAVE    72649 non-null  float64
 3   MAX_WAVE    72649 non-null  float64
 4   HPA         72649 non-null  float64
 5   일시          72649 non-null  datetime64[ns]
 6   특보강도        72649 non-null  float64
 7   남은시간        72649 non-null  float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 4.4 MB

In [25]:
df1 = df1.set_index('일시')
df1

,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,특보강도,남은시간
일시,,,,,,,
2011-03-04 17:00:00,0.110236,0.234957,0.053571,0.064103,0.698046,0.0,0.0
2011-03-04 18:00:00,0.133858,0.234957,0.053571,0.051282,0.710480,0.0,0.0
2011-03-04 19:00:00,0.177165,0.234957,0.053571,0.051282,0.719361,0.0,0.0
2011-03-04 20:00:00,0.114173,0.234957,0.053571,0.064103,0.726465,0.0,0.0
2011-03-04 21:00:00,0.149606,0.234957,0.053571,0.064103,0.735346,0.0,0.0
...,...,...,...,...,...,...,...
2018-10-06 06:00:00,0.535433,0.627507,0.517857,0.525641,0.296625,2.0,12.0
2018-10-06 07:00:00,0.570866,0.627507,0.589286,0.602564,0.259325,2.0,11.0
2018-10-06 08:00:00,0.696850,0.664756,0.839286,0.858974,0.206039,2.0,10.0
2018-10-06 09:00:00,0.661417,0.670487,0.642857,0.653846,0.150977,2.0,9.0
2018-10-06 10:00:00,1.000000,1.000000,1.000000,1.000000,0.087034,2.0,8.0

In [25]:
df1.to_csv('MinMax_model02.csv')