# Log 변환
* NaN 값이 나와서 사용하지 않기로 함

In [2]:
# 라이브러리 로드
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
# 데이터 로딩
df = pd.read_csv('./data/2011_2020_m2.ver2.csv', encoding='utf-8')
df

,일시,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,특보강도,남은시간
0,2011-03-04 17:00:00,2.8,8.9,0.3,0.5,1021.0,0.0,0.0
1,2011-03-04 18:00:00,3.4,8.9,0.3,0.4,1021.7,0.0,0.0
2,2011-03-04 19:00:00,4.5,8.9,0.3,0.4,1022.2,0.0,0.0
3,2011-03-04 20:00:00,2.9,8.9,0.3,0.5,1022.6,0.0,0.0
4,2011-03-04 21:00:00,3.8,8.9,0.3,0.5,1023.1,0.0,0.0
...,...,...,...,...,...,...,...,...
72644,2018-10-06 06:00:00,13.6,22.6,2.9,4.1,998.4,2.0,12.0
72645,2018-10-06 07:00:00,14.5,22.6,3.3,4.7,996.3,2.0,11.0
72646,2018-10-06 08:00:00,17.7,23.9,4.7,6.7,993.3,2.0,10.0
72647,2018-10-06 09:00:00,16.8,24.1,3.6,5.1,990.2,2.0,9.0
72648,2018-10-06 10:00:00,25.4,35.6,5.6,7.8,986.6,2.0,8.0

In [4]:
# 데이터셋 구성
df_tgt = df[['WIND_SPEED', 'GUST_WIND', 'SIG_WAVE', 'MAX_WAVE', 'HPA']]

* 로그

In [5]:
# 로그 
log_df_tgt=np.log(df_tgt)

c:\Python39\lib\site-packages\pandas\core\internals\blocks.py:351: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)

In [6]:
log_df_tgt

       WIND_SPEED  GUST_WIND  SIG_WAVE  MAX_WAVE       HPA
0        1.029619   2.186051 -1.203973 -0.693147  6.928538
1        1.223775   2.186051 -1.203973 -0.916291  6.929223
2        1.504077   2.186051 -1.203973 -0.916291  6.929712
3        1.064711   2.186051 -1.203973 -0.693147  6.930104
4        1.335001   2.186051 -1.203973 -0.693147  6.930593
...           ...        ...       ...       ...       ...
72644    2.610070   3.117950  1.064711  1.410987  6.906154
72645    2.674149   3.117950  1.193922  1.547563  6.904048
72646    2.873565   3.173878  1.547563  1.902108  6.901033
72647    2.821379   3.182212  1.280934  1.629241  6.897907
72648    3.234749   3.572346  1.722767  2.054124  6.894265

[72649 rows x 5 columns]

In [8]:
# 다시 '일시', '특보강도', '남은시간' 합침
df1 = pd.concat([log_df_tgt,df[['일시','특보강도','남은시간']]], axis=1)
df1

,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,일시,특보강도,남은시간
0,1.029619,2.186051,-1.203973,-0.693147,6.928538,2011-03-04 17:00:00,0.0,0.0
1,1.223775,2.186051,-1.203973,-0.916291,6.929223,2011-03-04 18:00:00,0.0,0.0
2,1.504077,2.186051,-1.203973,-0.916291,6.929712,2011-03-04 19:00:00,0.0,0.0
3,1.064711,2.186051,-1.203973,-0.693147,6.930104,2011-03-04 20:00:00,0.0,0.0
4,1.335001,2.186051,-1.203973,-0.693147,6.930593,2011-03-04 21:00:00,0.0,0.0
...,...,...,...,...,...,...,...,...
72644,2.610070,3.117950,1.064711,1.410987,6.906154,2018-10-06 06:00:00,2.0,12.0
72645,2.674149,3.117950,1.193922,1.547563,6.904048,2018-10-06 07:00:00,2.0,11.0
72646,2.873565,3.173878,1.547563,1.902108,6.901033,2018-10-06 08:00:00,2.0,10.0
72647,2.821379,3.182212,1.280934,1.629241,6.897907,2018-10-06 09:00:00,2.0,9.0
72648,3.234749,3.572346,1.722767,2.054124,6.894265,2018-10-06 10:00:00,2.0,8.0

In [9]:
print('feature 들의 평균 값')
print(df1.mean())
print('\nfeature 들의 분산 값')
print(df1.var())

feature 들의 평균 값
WIND_SPEED        -inf
GUST_WIND     2.230755
SIG_WAVE          -inf
MAX_WAVE          -inf
HPA           6.922413
특보강도          0.090504
남은시간          1.444576
dtype: float64

feature 들의 분산 값
WIND_SPEED          NaN
GUST_WIND      0.209054
SIG_WAVE            NaN
MAX_WAVE            NaN
HPA            0.000054
특보강도           0.094124
남은시간          41.097588
dtype: float64

C:\Users\dbwjd\AppData\Local\Temp\ipykernel_19384\2957119008.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df1.mean())
C:\Users\dbwjd\AppData\Local\Temp\ipykernel_19384\2957119008.py:4: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df1.var())

## 다른 방법

In [28]:
df['log_WIND_SPEED']=np.log(df['WIND_SPEED'])
df['log_GUST_WIND']=np.log(df['GUST_WIND'])
df['log_SIG_WAVE']=np.log(df['SIG_WAVE'])
df['log_MAX_WAVE']=np.log(df['MAX_WAVE'])
df['log_HPA']=np.log(df['HPA'])

In [29]:
df

,일시,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,특보강도,log_WIND_SPEED,log_GUST_WIND,log_SIG_WAVE,log_MAX_WAVE,log_HPA
0,2012-08-02 04:00:00,8.5,15.0,0.6,1.0,1007.8,1.0,2.140066,2.708050,-0.510826,0.000000,6.915525
1,2018-06-15 18:00:00,8.9,16.0,0.6,0.9,1011.5,1.0,2.186051,2.772589,-0.510826,-0.105361,6.919190
2,2018-04-24 12:00:00,4.8,13.8,0.5,0.7,1008.0,1.0,1.568616,2.624669,-0.693147,-0.356675,6.915723
3,2018-03-22 06:00:00,2.4,11.2,1.6,2.2,1011.9,1.0,0.875469,2.415914,0.470004,0.788457,6.919585
4,2018-03-17 08:00:00,4.9,9.4,0.6,0.9,1030.7,1.0,1.589235,2.240710,-0.510826,-0.105361,6.937993
...,...,...,...,...,...,...,...,...,...,...,...,...
199504,2018-03-20 10:00:00,14.7,27.1,2.2,3.2,1023.1,2.0,2.687847,3.299534,0.788457,1.163151,6.930593
199505,2012-04-03 07:00:00,5.4,17.1,1.1,1.7,992.8,2.0,1.686399,2.839078,0.095310,0.530628,6.900529
199506,2018-07-03 20:00:00,15.8,27.5,2.3,3.4,988.0,2.0,2.760010,3.314186,0.832909,1.223775,6.895683
199507,2018-03-20 09:00:00,13.5,25.3,2.0,2.9,1022.3,2.0,2.602690,3.230804,0.693147,1.064711,6.929810
199508,2018-03-22 03:00:00,3.3,11.2,1.6,2.3,1011.1,2.0,1.193922,2.415914,0.470004,0.832909,6.918794

In [24]:
df.head()

,일시,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,특보강도,남은시간,log_WIND_SPEED,log_GUST_WIND,log_SIG_WAVE,log_MAX_WAVE,log_HPA
0,2011-03-04 17:00:00,2.8,8.9,0.3,0.5,1021.0,0.0,0.0,1.029619,2.186051,-1.203973,-0.693147,6.928538
1,2011-03-04 18:00:00,3.4,8.9,0.3,0.4,1021.7,0.0,0.0,1.223775,2.186051,-1.203973,-0.916291,6.929223
2,2011-03-04 19:00:00,4.5,8.9,0.3,0.4,1022.2,0.0,0.0,1.504077,2.186051,-1.203973,-0.916291,6.929712
3,2011-03-04 20:00:00,2.9,8.9,0.3,0.5,1022.6,0.0,0.0,1.064711,2.186051,-1.203973,-0.693147,6.930104
4,2011-03-04 21:00:00,3.8,8.9,0.3,0.5,1023.1,0.0,0.0,1.335001,2.186051,-1.203973,-0.693147,6.930593

In [10]:
df1.head(5)

,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,일시,특보강도,남은시간
0,1.029619,2.186051,-1.203973,-0.693147,6.928538,2011-03-04 17:00:00,0.0,0.0
1,1.223775,2.186051,-1.203973,-0.916291,6.929223,2011-03-04 18:00:00,0.0,0.0
2,1.504077,2.186051,-1.203973,-0.916291,6.929712,2011-03-04 19:00:00,0.0,0.0
3,1.064711,2.186051,-1.203973,-0.693147,6.930104,2011-03-04 20:00:00,0.0,0.0
4,1.335001,2.186051,-1.203973,-0.693147,6.930593,2011-03-04 21:00:00,0.0,0.0

In [11]:
df1['일시'] = pd.to_datetime(df1['일시'])
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72649 entries, 0 to 72648
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   WIND_SPEED  72649 non-null  float64
 1   GUST_WIND   72649 non-null  float64
 2   SIG_WAVE    72649 non-null  float64
 3   MAX_WAVE    72649 non-null  float64
 4   HPA         72649 non-null  float64
 5   일시          72649 non-null  datetime64[ns]
 6   특보강도        72649 non-null  float64
 7   남은시간        72649 non-null  float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 4.4 MB

In [12]:
df1 = df1.set_index('일시')
df1

,WIND_SPEED,GUST_WIND,SIG_WAVE,MAX_WAVE,HPA,특보강도,남은시간
일시,,,,,,,
2011-03-04 17:00:00,1.029619,2.186051,-1.203973,-0.693147,6.928538,0.0,0.0
2011-03-04 18:00:00,1.223775,2.186051,-1.203973,-0.916291,6.929223,0.0,0.0
2011-03-04 19:00:00,1.504077,2.186051,-1.203973,-0.916291,6.929712,0.0,0.0
2011-03-04 20:00:00,1.064711,2.186051,-1.203973,-0.693147,6.930104,0.0,0.0
2011-03-04 21:00:00,1.335001,2.186051,-1.203973,-0.693147,6.930593,0.0,0.0
...,...,...,...,...,...,...,...
2018-10-06 06:00:00,2.610070,3.117950,1.064711,1.410987,6.906154,2.0,12.0
2018-10-06 07:00:00,2.674149,3.117950,1.193922,1.547563,6.904048,2.0,11.0
2018-10-06 08:00:00,2.873565,3.173878,1.547563,1.902108,6.901033,2.0,10.0
2018-10-06 09:00:00,2.821379,3.182212,1.280934,1.629241,6.897907,2.0,9.0
2018-10-06 10:00:00,3.234749,3.572346,1.722767,2.054124,6.894265,2.0,8.0

* 저장

In [21]:
df1.to_csv('MODEL_VER2_Log.csv')